name : Docker Build

on :
  push :
    branches :
      - ci-testing
      - main
      - stable
    tags :
      - '*'
  schedule :
    - cron : '0 2 * * 0' # Weekly on Sundays at 02:00

jobs :
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name : Login to GitHub Container Registry
        uses : docker/login-action@v1
        with :
          registry : ghcr.io
          username : ${{ github.repository_owner }}
          password : ${{ secrets.GITHUB_TOKEN }}

      - name : Build Docker Metadata
        id : meta
        uses : crazy-max/ghaction-docker-meta@v2
        with :
          images : |
            azuracast/azuracast_radio
            ghcr.io/azuracast/radio
          tags : |
            type=raw,value=latest,enable=${{ endsWith(github.ref, github.event.repository.default_branch) }}
            type=ref,event=branch
            type=semver,pattern={{version}}

      - name : Publish to Docker Hub
        uses : docker/build-push-action@v2
        with :
          context : .
          # platforms : linux/amd64,linux/arm64
          cache-from : type=registry,ref=azuracast/azuracast_radio:latest
          push : true
          tags : ${{ steps.meta.outputs.tags }}
          labels : ${{ steps.meta.outputs.labels }}