name : Docker Build

on :
  push :
    branches :
      - ci-testing
      - main
      - stable
  schedule :
    - cron : '0 2 * * 0' # Weekly on Sundays at 02:00

jobs :
  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name : Determine Tag Name
        id : tag
        run : |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          if [ $BRANCH_NAME == 'main' ]; then
            BRANCH_NAME="latest"
          fi

          echo "::set-output name=TAG::${BRANCH_NAME}"

      - name : Publish to Docker Hub
        uses : docker/build-push-action@v2
        with :
          context: .
          # platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=azuracast/azuracast_radio:${{ steps.tag.outputs.TAG }}
          tags : azuracast/azuracast_radio:${{ steps.tag.outputs.TAG }}
          push : true